# Generated by Django 5.0.4 on 2024-05-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delhi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delhi',
            options={'ordering': ['lastname', 'firstname'], 'verbose_name_plural': 'Delhi Members'},
        ),
        migrations.AddField(
            model_name='delhi',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delhi',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delhi',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delhi',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='delhi',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='delhi',
            name='firstname',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='delhi',
            name='lastname',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
    ]
