# Generated by Django 4.2.3 on 2024-05-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delhi', '0003_login_tender_delete_delhi'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='Status',
            field=models.CharField(default='OK', max_length=100),
        ),
    ]
